name: swdbg_log_app
description: 'An app that allows logging turns of Star Wars: The Deckbuilding Game.'
publish_to: 'none'
version: 0.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  collection: ^1.17.1
  cr_file_saver: ^0.0.2+1
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.17
  flutter_svg: ^2.0.7
  meta: ^1.9.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  neodart: ^0.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
